import pandas as pd
from datetime import date
from src.shared.db import get_db_connection

def generate_spx_commentary(score_row, feature_row):
    """
    Generates rule-based commentary for SPX.
    """
    instability = score_row.get('instability_index', 50)
    regime = score_row.get('regime', 'FRAGILE')
    net_gamma = feature_row.get('net_gamma', 0)
    gamma_slope = feature_row.get('gamma_slope', 0)
    
    # Regime Commentary
    intro = ""
    if regime == "EXPLOSIVE":
        intro = "SPX is in an EXPLOSIVE regime. Dealer positioning is fragile, and flows are likely to amplify volatility rather than dampen it."
    elif regime == "STABLE":
        intro = "SPX is in a STABLE regime. Dealer flows are supportive and likely to suppress volatility."
    else:
        intro = "SPX is in a FRAGILE regime. Market structure is mixed, creating a path-dependent environment."

    # Gamma Commentary
    gamma_note = ""
    if net_gamma < 0:
        gamma_note = "With Net Gamma deeply negative, dealers are forced to hedge in the direction of the trend (selling into drops, buying into rallies), creating asymmetric risk."
    elif net_gamma > 0:
        gamma_note = "Positive Net Gamma implies dealers are acting as mean-reversion agents, selling rips and buying dips."
        
    return f"{intro} {gamma_note}"

def generate_report(as_of: date):
    """
    Generates the full markdown report for a given date.
    """
    print(f"Generating report for {as_of}...")
    
    with get_db_connection() as conn:
        # Fetch Scores
        scores_df = pd.read_sql("SELECT * FROM asset_scores WHERE as_of = %s", conn, params=(as_of,))
        # Fetch Features
        equity_df = pd.read_sql("SELECT * FROM features_equity WHERE as_of = %s", conn, params=(as_of,))
        
    if scores_df.empty:
        print(f"No scores found for {as_of}")
        return None
        
    # Prepare Data
    spx_score = scores_df[scores_df['symbol'] == 'SPX'].iloc[0] if not scores_df[scores_df['symbol'] == 'SPX'].empty else {}
    spx_features = equity_df.iloc[0] if not equity_df.empty else {}
    
    # Generate Commentary
    spx_commentary = generate_spx_commentary(spx_score, spx_features)
    
    # Fill Template
    report = f"""# DealerFlow Weekly Macro Flow Report
**Date:** {as_of}

## 1. Global Flow Map (Summary)

| Asset | Instability | Regime | Pressure |
|-------|-------------|--------|----------|
| **SPX** | {spx_score.get('instability_index', 'N/A')} | **{spx_score.get('regime', 'N/A')}** | {spx_score.get('pressure_direction', 'N/A')} |
| **GOLD** | N/A | *Pending* | N/A |
| **AUDUSD** | N/A | *Pending* | N/A |

---

## 2. Equity Flow Snapshot (SPX)

**🧠 Structural Signals**
*   **Net Gamma:** {float(spx_features.get('net_gamma', 0)):.2f} (Normalized)
*   **Gamma Slope:** {float(spx_features.get('gamma_slope', 0)):.4f}
*   **Net Delta:** {float(spx_features.get('net_delta', 0)):.2f}

**📌 Interpretation**
{spx_commentary}

---

## 3. Cross-Asset Themes
*   *Pending integration of Gold and FX modules.*
*   Equity instability suggests a cautious approach to risk assets.

---

## 4. Disclaimer
This report is an automated structural-flow viewpoint generated by the DealerFlow engine.
It is not trading advice — purely a technical research signal.
"""
    
    return report

def save_report(report_content, as_of):
    filename = f"report_{as_of}.md"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report_content)
    print(f"Report saved to {filename}")
